### PR TITLE
Edit script for accomodating SqlManagementMode changes

### PR DESCRIPTION
**Pull request by veppala**
## Description

This PR updates the script for:
1. Accommodate SqlManagementMode change for Get-AzSqlVM cmdlet
2. Powershell 7 compatible script 

## Checklist

- [ ] This pull request was tested on __both of__:
  - [X] PowerShell 5.1 (Windows)
  - [ ] PowerShell 6.x
  - [X] PowerShell 7.x ([Latest PowerShell](https://github.com/PowerShell/PowerShell/releases))
- [X] Scripts do not contain static passwords or other secret tokens.
- [X] All Azure resource identifiers which must be universally unique are guaranteed to be so.

### Testing information

**Powershell 7.3.4**:
PS C:\> [pscustomobject]$PSVersionTable | Select-Object OS, BuildVersion, PSVersion
OS                           BuildVersion PSVersion
Microsoft Windows 10.0.22621              7.3.4

PS C:\> (Get-InstalledModule -Name Az).Version
10.0.0

**Powershell 5.1:**
PS C:\> [pscustomobject]$PSVersionTable | Select-Object OS, BuildVersion, PSVersion
OS BuildVersion   PSVersion    
   10.0.22621.963 5.1.22621.963

PS C:\> (Get-InstalledModule -Name Az).Version
Major  Minor  Build  Revision
6      4      0      -1

### CODE REVIEW

**Comment by veppala** [comment]
@mikefrobbins - Could you please check and merge this PR when you get a chance?

**Comment by mikefrobbins** [comment]
@veppala:

-  Please resolve the merge conflict referenced in the build error.
- Supply the URL to the Azure PowerShell article where the code is referenced. This repo is only for code snippets used in the official Microsoft Azure PowerShell documentation.
- This appears to be a PowerShell module and it's recommended to publish modules in the PowerShell Gallery for ease of installation by customers.

**Comment by ebruersan** [comment]
> @veppala:
> 
> * Please resolve the merge conflict referenced in the build error.
> * Supply the URL to the Azure PowerShell article where the code is referenced. This repo is only for code snippets used in the official Microsoft Azure PowerShell documentation.
> * This appears to be a PowerShell module and it's recommended to publish modules in the PowerShell Gallery for ease of installation by customers.

Hi @mikefrobbins, would it be ok if we reference it from SQL VM documentation (it would be from this page: https://learn.microsoft.com/en-us/azure/azure-sql/virtual-machines/windows/sql-agent-extension-troubleshoot-known-issues?view=azuresql? We have done this before as you can see in https://github.com/Azure/azure-docs-powershell-samples/tree/master/sql-virtual-machine with register-sql-vms, for example. So I am hoping we can follow the same pattern.

**Review by mikefrobbins — APPROVED** [review]
LGTM

**Pull request merged**
