### PR TITLE
Adding Cassandra & Table sample

### PR DESCRIPTION
**Pull request by SnehaGunda**

### CODE REVIEW

**Comment by SnehaGunda** [comment]
Fixes https://github.com/MicrosoftDocs/azure-docs/issues/13063

**Comment by SnehaGunda** [comment]
#sign-off

**Comment by SnehaGunda** [comment]
@erickson-doug Can you please merge this PR.

**Comment by erickson-doug** [comment]
done!

--
Doug Erickson (douge) -- 425 273 1304

________________________________

**Pull request merged**
