### PR TITLE
First managed instance create script

### PR DESCRIPTION
**Pull request by CarlRabeler**

### CODE REVIEW

**Comment by CarlRabeler** [comment]
@sptramer please merge - FYI - this script will take a minimum of 3 hours to complete (and an MI is expensive, so if you create, be aware - and delete once you are done)

**Comment by CarlRabeler** [comment]
#hold-off we decided to add one more step to this script

**Comment by sptramer** [comment]
@CarlRabeler Ping again when the script is ready.

**Comment by CarlRabeler** [comment]
Will do – waiting on product group….

**Comment by CarlRabeler** [comment]
@sptramer Hi - please merge - this script is ready to go

**Pull request merged**
