### PR TITLE
Updated Az commands to support V2.

### PR DESCRIPTION
**Pull request by KranthiPakala-MSFT**
## Description

Updated Az commands to support DataFactory V2 which resolves https://github.com/MicrosoftDocs/azure-docs/issues/37039

## Checklist

- [x] This pull request was tested on __both of__:
  - [x] PowerShell 5.1 (Windows)
  - [x] PowerShell 6.x ([Latest PowerShell](https://github.com/PowerShell/PowerShell/releases))
- [x] Scripts do not contain static passwords or other secret tokens.
- [x] All Azure resource identifiers which must be universally unique are guaranteed to be so.

### Testing information

Platform:

Powershell version: `$PSVersionTable.PSVersion`

Az version: `(Get-InstalledModule -Name Az).Version`

### CODE REVIEW

**Comment by sptramer** [comment]
@KranthiPakala-MSFT Please confirm a test on PowerShell 6.x and then I will start review. Thanks!

**Comment by KranthiPakala-MSFT** [comment]
@sptramer I have completed testing PS commands in latest Powershell 6.x and everything is working as expected. Could you please review and approve the changes.

**Comment by djpmsft** [comment]
@sptramer The PR itself only updates a few commands. The change you recommended is a bit more intensive. Can we push this incremental change to unblock a few users?

**Comment by sptramer** [comment]
@djpmsft The changes are actually not extensive. I'm pretty sure it's easy to change a write to the absolute path `C:\` to the relative path `./`. That would be the recommended fix and it is simple enough that it should be made before merge.

**Comment by sdwheeler** [comment]
@KranthiPakala-MSFT Please change the references `C:\` to `./` as requested. This solves two issues:

1. Makes the script work on all platforms
2. Avoids writing files in the root of the `C:` drive on Windows, which will fail unless you are running elevated.

**Comment by KranthiPakala-MSFT** [comment]
@sdwheeler Thanks for bumping this up.  This is impacting multiple docs where this powershell script is referenced. And the docs have 'C:\' everywhere, so I will escalate this to the doc author internally, but will close this PR for now. 

@djpmsft for awareness.

**Pull request closed without merging**
