### PR TITLE
bug fix in failover priority script

### PR DESCRIPTION
**Pull request by markjbrown**
## CHECKLIST

- [ ] This pull request was tested on:
  - [ ] PowerShell 5.1 on Windows
  - [ ] PowerShell 6.x on Windows
  - [ ] PowerShell 6.x on Linux
- [ ] Resources not created by the scripts in the pull request are __explicitly__ mentioned in a comment at the head of the file, __and__ have user-supplied variables or function arguments which correspond to the required resource identifiers.
- [ ] All user-supplied values are set in variables at the head of the file, after any comments.
- [ ] All passwords are user-supplied values, or generated by a secure random string generator.
- [ ] All Azure identifiers required to be universally unique are guaranteed to be so. 
- [ ] All scripts only use commands available in the latest release of the Azure PowerShell `Az` module. ([Command reference](https://docs.microsoft.com/en-us/powershell/module/?term=Az.))
  - [ ] I have an exception! (__optional__ - state for which service)
  - [ ] I'm requesting an exception! (__optional__ - you must include your MS alias for further discussion before PR review)
- [ ] All scripts contain only ASCII characters (no 'smart quotes' or other wide characters)

### CODE REVIEW

**Comment by markjbrown** [comment]
@tysonn @SnehaGunda hey Tyson and Sneha, can someone merge this? Thanks.

**Comment by sptramer** [comment]
@markjbrown Please complete the required checklist. PRs without a completed checklist will be closed after 7 days.

**Comment by SnehaGunda** [comment]
@markjbrown You script uses all the instructions in the checklist except "user-supplied values are variables"

can you please add couple more variables at the beginning of the script and update the command to:

$apiVersion = "2015-04-08" 
$resourceType = "Microsoft.DocumentDb/databaseAccounts"

Invoke-AzResourceAction -Action failoverPriorityChange `
    -ResourceType $resourceType -ApiVersion $apiVersion`
    -ResourceGroupName $resourceGroupName -Name $accountName -Parameters $failoverPolicies

Thanks,
Sneha

**Comment by SnehaGunda** [comment]
Fixes https://github.com/MicrosoftDocs/azure-docs/issues/31781

**Comment by SnehaGunda** [comment]
@markjbrown I submitted a PR to your PR to update the script: https://github.com/markjbrown/azure-docs-powershell-samples/pull/1 can you please merge and signoff on this PR.

**Comment by markjbrown** [comment]
I have merged @SnehaGunda 's changes. @sptramer  this is ready to be merged.

Thanks.

**Comment by sptramer** [comment]
The PR checklist was not completed within the required timeframe. Closing this pull request. You may reopen it when the checklist is completed.

**Comment by NavtejSaini-MSFT** [comment]
The document script didnt change after this PR as well. Please check.

**Pull request closed without merging**
