### PR TITLE
Add script to fetch SQL VM extension health status

### PR DESCRIPTION
**Pull request by veppala**
## Description

This script finds all SQL VMs currently running Full mode and gets the Extension Health status. At the end script will report the Extension Health status of each SQL VM in a subscription or list of subscriptions.

## Checklist

- [X] Scripts do not contain static passwords or other secret tokens.
- [X] This pull request was tested on __both of__:
  - [X] PowerShell 5.1 (Windows)
  - [ ] PowerShell 6.x
  - [X] PowerShell 7.x ([Latest PowerShell](https://github.com/PowerShell/PowerShell/releases))
- [X] All Azure resource identifiers which must be universally unique are guaranteed to be so.

### Testing information

Platform and PowerShell version: 
OS: Microsoft Windows
BuildVersion: 10.0.22621.963
PSVersion: 5.1.22621.963
Az Version: 6.4.0

OS: Microsoft Windows
BuildVersion: 10.0.22621
PSVersion: 7.3.4
Az Version: 6.4.0

### CODE REVIEW

**Comment by mikefrobbins** [comment]
@veppala Please provide the URL to the article (doc) where this script is referenced. This repo is only for Azure PowerShell code samples used in Microsoft's official Azure PowerShell Documentation.

**Comment by veppala** [comment]
> @veppala Please provide the URL to the article (doc) where this script is referenced. This repo is only for Azure PowerShell code samples used in Microsoft's official Azure PowerShell Documentation.

@mikefrobbins  to my understanding, this script will be used in Microsoft official documentation. I believe the documentation has not been published because we needed the script in order to announce (what the script is intending to do). The PMs of these feature Aditya Badramraju and Pam Lahoud have been asked to confirm the usage of this script/ and provide links if necessary.

@adbadram can confirm

**Comment by mikefrobbins** [comment]
@veppala Merging this PR on a tentative basis. I've added an ADO item to follow-up in 90 days and remove the sample if it's not used in a doc since this repo is only for samples that are used in the official Azure PowerShell documentation.

**Review by mikefrobbins — APPROVED** [review]
URL to official Azure PowerShell documentation where this code is used to be provided by service team, otherwise LGTM.

**Pull request merged**
