### PR TITLE
Create KB4088787_Fix.ps1

### PR DESCRIPTION
**Pull request by jc-mackin**
## Checklist

- [ ] This pull request was tested on __both of__:
  - [ ] PowerShell 5.1 (Windows)
  - [ ] PowerShell 6.x
  - [ ] PowerShell 7.x ([Latest PowerShell](https://github.com/PowerShell/PowerShell/releases))
- [ ] Scripts do not contain static passwords or other secret tokens.
- [ ] All Azure resource identifiers which must be universally unique are guaranteed to be so.

### Testing information

Platform and PowerShell version: `[pscustomobject]$PSVersionTable | Select-Object OS, BuildVersion, PSVersion`

Az version: `(Get-InstalledModule -Name Az).Version`

### CODE REVIEW

**Comment by JarrettRenshaw** [comment]
#sign-off

**Comment by JarrettRenshaw** [comment]
@mikefrobbins I am a Content PM in CSS Content, and working with an escalation engineer to publish a PowerShell script. It has been tested and vetted by Support and our writer JC Mackin has created this PR for it. Can you let us know if you can merge this PR or if there is anything else you need from us? Thanks!

**Comment by mikefrobbins** [comment]
@JarrettRenshaw Is this script Azure PowerShell related? It does not appear to use any Azure PowerShell related cmdlets. This repo is specifically for Azure PowerShell sample scripts. Looping in @dcaro

**Comment by jc-mackin** [comment]
@mikefrobbins This script is only indirectly related to Azure. It fixes a problem in AD FS, which as you know is often used for SSO authentication in connecting Azure and on-prem deployments.  However, it doesn't use any Azure PowerShell cmdlets. If this isn't the correct repo, would you be able to recommend another that is more suitable?

**Comment by dcaro** [comment]
The purpose of this repo is to give scenario oriented samples how to manage Azure resources with PowerShell.
Since this script aims at fixing an issue with ADFS, I think that this script should be on a different repo or directly in the KB article.
@jc-mackin unfortunately I do not have any pointers.

**Comment by mikefrobbins** [comment]
There's a [process for onboarding examples](https://review.docs.microsoft.com/help/contribute/samples/). The only other option I'm aware of that hasn't already been mentioned would be to publish it to the [PowerShell Gallery](https://www.powershellgallery.com/) where users could install it using the [Install-Script](https://docs.microsoft.com/powershell/module/powershellget/install-script) cmdlet.

**Pull request closed without merging**
