### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by j0rt3g4**
Solving Issue on Source code:
https://github.com/MicrosoftDocs/azure-docs/issues/30743
On PR #236

### CODE REVIEW

**Comment by cynthn** [comment]
@sptramer

**Comment by sptramer** [comment]
@j0rt3g4 Please only submit pull requests where you have completed the checklist. This is a requirement, as outlined in the PR template. My time is so limited for PR processing that I can't devote time to examining or testing that people have followed the basic requirements for submission.

**Comment by sptramer** [comment]
Reopening at request of @cynthn.

**Comment by cynthn** [comment]
@j0rt3g4 Thank you for the contribution! I'll work with my team to get this fix merged into the script file :)

**Comment by j0rt3g4** [comment]
I'm sorry @sptramer my time is valuable as well and I honestly don't know what you're talking about.

**Comment by cynthn** [comment]
## Description

Customer helped by removing random characters and fixing an issue with the the reference to the storage type.

## Checklist



- [x] This pull request was tested on __both of__:
  - [x] PowerShell 5.1 (Windows)
  - [x] PowerShell 6.x ([Latest PowerShell](https://github.com/PowerShell/PowerShell/releases))
- [x] Scripts do not contain static passwords or other secret tokens.
- [x] All Azure resource identifiers which must be universally unique are guaranteed to be so.

### Testing information



Platform:

Powershell version: `$PSVersionTable.PSVersion`

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      18362  145 

Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
6      2      2


Az version: `(Get-InstalledModule -Name Az).Version`

PS Azure:\> (Get-InstalledModule -Name Az).Version
2.6.0

Major  Minor  Build  Revision
-----  -----  -----  --------
2      5      0      -1

**Comment by cynthn** [comment]
@sptramer Tested it locally and in CloudShell. See checklist above for details.

**Comment by sptramer** [comment]
Sorry, that was much too snarky. The [checklist is part of the pull request template](https://github.com/Azure/azure-docs-powershell-samples/blob/master/.github/pull_request_template.md) and this is a standard process for any github repo that has requirements for beginning pull processing.

**Comment by Karishma-Tiwari-MSFT** [comment]
@cynthn Is this ready to be merged or any update needed? Let me know. Thanks :)

**Comment by cynthn** [comment]
@sptramer I'm not understanding where you hit an issue. I tested this myself, using an existing snapshot, and it worked fine in both CloudShell and locally. Can you send me the version of the script you used?

**Comment by cynthn** [comment]
@sptramer Sorry, tested the wrong version... yes, there is something wrong with this and I'm trying to track it down. There were 2 separate scripts (one was OS disk and the other was just a disk) with similar issues and similar syntax. You are correct, this one still isn't working. I will pull this over into my fork and try to find the issue. Sorry for the mis-direction!

**Comment by cynthn** [comment]
#please-close @sptramer I found the issue and filed a PR that has the changes from @j0rt3g4 plus an additional fix to update the parameter for specifying the storage type. The new PR is: https://github.com/Azure/azure-docs-powershell-samples/pull/238

**Pull request closed without merging**
