### PR TITLE
MicrosoftDocs/azure-docs#31980

### PR DESCRIPTION
**Pull request by MicahMcKittrick-MSFT**
## CHECKLIST

- [ ] This pull request was tested on:
  - [ ] PowerShell 5.1 on Windows
  - [ ] PowerShell 6.x on Windows
  - [ ] PowerShell 6.x on Linux
- [ ] Resources not created by the scripts in the pull request are __explicitly__ mentioned in a comment at the head of the file, __and__ have user-supplied variables or function arguments which correspond to the required resource identifiers.
- [ ] All user-supplied values are set in variables at the head of the file, after any comments.
- [ ] All passwords are user-supplied values, or generated by a secure random string generator.
- [ ] All Azure identifiers required to be universally unique are guaranteed to be so. 
- [ ] All scripts only use commands available in the latest release of the Azure PowerShell `Az` module. ([Command reference](https://docs.microsoft.com/en-us/powershell/module/?term=Az.))
  - [ ] I have an exception! (__optional__ - state for which service)
  - [ ] I'm requesting an exception! (__optional__ - you must include your MS alias for further discussion before PR review)
- [ ] All scripts contain only ASCII characters (no 'smart quotes' or other wide characters)

### CODE REVIEW

**Comment by MicahMcKittrick-MSFT** [comment]
#sign-off

**Comment by sptramer** [comment]
@MicahMcKittrick-MSFT  Please complete the required checklist. PRs without a completed checklist will be closed after 7 days.

**Comment by MicahMcKittrick-MSFT** [comment]
@sptramer I can check all the boxes if needed. All that was changed was removing strange characters from the script

https://github.com/MicrosoftDocs/azure-docs/issues/31980

image

**Comment by sptramer** [comment]
@MicahMcKittrick-MSFT Please make sure you actually perform the tasks associated with any boxes you check, but yes, you are now __required__ to perform these steps for any PR, no matter how small.

**Comment by MicahMcKittrick-MSFT** [comment]
Got it. I will just close this then and have the authors review who likely have push access. Thanks though!

**Pull request closed without merging**
