### PR TITLE
Changed PS Script

### PR DESCRIPTION
**Pull request by VanMSFT**

### CODE REVIEW

**Comment by VanMSFT** [comment]
@sptramer - Hi Steven, can you please help merge this file. Thanks!

**Comment by VanMSFT** [comment]
@CarlRabeler @MladjoA FYI

**Comment by VanMSFT** [comment]
@sptramer Hey Stephen - I wanted to follow-up on this.
@CarlRabeler @MladjoA - FYI

**Comment by CarlRabeler** [comment]
@erickson-doug Can you help us here?

**Comment by CarlRabeler** [comment]
@VanMSFT please review

**Comment by erickson-doug** [comment]
Argh, I just blind merged this. My bad. Can we get this fixed?

**Comment by VanMSFT** [comment]
@erickson-doug @sptramer - Thanks for merging! The script came from our PM, and it worked for him. Let me know if there's something I need to fix. I will try to update the article that pulls this PS script.

**Comment by sptramer** [comment]
@VanMSFT Please fix the requested changes and put them into a new pull request. @erickson-doug I'll make a PR that reverts this change and merge it.

**Comment by VanMSFT** [comment]
@sptramer Will try. Quick question - what am I looking to fix? I didn't see any errors when I created the pull request. I also put the script into notepad++ and didn't see any special characters. Thanks!

**Comment by VanMSFT** [comment]
@MladjoA Hey Mladen - Can you run the PS code again and verify that it's working? It seems that the one we copied and pasted from the following link will not let us merge:

https://microsoft.sharepoint.com/teams/sqlcloudlifter/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2Fsqlcloudlifter%2FShared%20Documents%2FTDE%2Fsetup%2Dtde%2Dbyok%2Dsqlmi%2Eps1&parent=%2Fteams%2Fsqlcloudlifter%2FShared%20Documents%2FTDE&p=true&slrid=2022b49e-5000-0000-b333-d5b864e3770f

Thanks!

**Comment by sptramer** [comment]
@VanMSFT See the requested changes: https://github.com/Azure/azure-docs-powershell-samples/pull/162#pullrequestreview-191812412

There is no automated run on the powershell scripts repo. You need to manually run the script and test before making a pull request.

**Comment by MladjoA** [comment]
@sptramer The script works perfectly in Windows Power Shell ISE. The only thing that comes to my mind is that we may try with additional Enter/blank line at the end.

**Comment by sptramer** [comment]
It might work in ISE, but it does not work in the command line. I tried adding a newline at the end of the file and that did not resolve the problem.

**Comment by sptramer** [comment]
Attempted a run in ISE:

```
PS C:\Users\sttramer\src\azure-docs-powershell-samples\sql-database\transparent-data-encryption> .\setup-tde-byok-sqlmi.ps1
At C:\Users\sttramer\src\azure-docs-powershell-samples\sql-database\transparent-data-encryption\setup-tde-byok-sqlmi.
ps1:5 char:36
+ Set-AzureRmContext -SubscriptionId <subscription ID>
+                                    ~
The '<' operator is reserved for future use.
At C:\Users\sttramer\src\azure-docs-powershell-samples\sql-database\transparent-data-encryption\setup-tde-byok-sqlmi.
ps1:43 char:146
+ ... yVault -ManagedInstanceName "MyManagedInstance" -ResourceGroup "MyRG"
+                                                                         ~
The string is missing the terminator: ".
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : RedirectionNotSupported
```

The same issue regarding the terminator character appears.

**Comment by VanMSFT** [comment]
I created another PR: https://github.com/Azure/azure-docs-powershell-samples/pull/164

There were really only 2 changes in this PR, which I manually entered into the new PR. -Name was changed to -ManagedInstanceName. I also changed <subscription ID> to "subscription ID".

cc: @sptramer @MladjoA @CarlRabeler

**Pull request merged**
