### PR TITLE
add managed instance to a failover group

### PR DESCRIPTION
**Pull request by MashaMSFT**
## Checklist

- [ ] This pull request was tested on __both of__:
  - [ x] PowerShell 5.1 (Windows)
  - [ x] PowerShell 6.x ([Latest PowerShell](https://github.com/PowerShell/PowerShell/releases))
- [x ] Scripts do not contain static passwords or other secret tokens.
- [x ] All Azure resource identifiers which must be universally unique are guaranteed to be so.

only the managed instance script was tested this time. the other two scripts (the single database and elastic pool ones) were not tested again; the only thing that was changed was the getrandom variable. 
### Testing information

Platform:
windows 10
powershell 5      1      18362  145
az 2      4      0      -1

windows 10
powershell 6      2      1
az  2.4.0

Powershell version: `$PSVersionTable.PSVersion`

Az version: `(Get-InstalledModule -Name Az).Version`

### CODE REVIEW

**Comment by MashaMSFT** [comment]
@sptramer #sign-off

**Comment by MashaMSFT** [comment]
#hold-off

just realized removing the RG may not remove the MI, need to rethink clean up

**Comment by MashaMSFT** [comment]
@sptramer , #sign-off
i added an extra remove resource group cmdlet with a note explaining why we're doing that.. however i'm still waiting for PG approval that the wording is okay. can we test the script in the meantime? it's going to take a while to test... thanks!

**Comment by sptramer** [comment]
As long as the only changes after test will be copy/comment changes, I'm happy to start testing now. Thanks!

**Comment by MashaMSFT** [comment]
hi @sptramer, just wanted to check on the status of this?

**Comment by sptramer** [comment]
@MashaMSFT There are some issues with my ability to test because of limitations on my subscription being able to create managed instances, and many regions blocking the creation of Azure SQL resources (whether that's a limitation on my account or otherwise is unknown.) I'm working on figuring out the exact problem and finding who can help me resolve it.

**Comment by MashaMSFT** [comment]
hi @sptramer , please be sure to use east and east us 2 as the regions for MI deployment, and if that doesn't work, request an increase: aka.ms/sql-mi-obtain-larger-quota

thanks!

**Comment by sptramer** [comment]
@MashaMSFT Currently getting a failure from `./sql-database/failover-groups/add-managed-instance-to-failover-group-az-ps.ps1` - looking into it some more to see if it's a configuration problem on my end or a script issue.

When this PR is ready to merge, do you want to make copy edits here, or in a future PR?

**Comment by MashaMSFT** [comment]
@sptramer , here please :)

**Comment by sptramer** [comment]
OK, so I have conducted further testing. After contacting support, they were unable to see any reason why my subscription would be causing this error:

```
New-AzSqlInstance : Long running operation failed with status 'Failed'. Additional Info:'The deployment request failed because it would exceed total number of vCores (8) and/or subnets (1), which is above the al
lowance for your subscription: max vCores: 0, max number of subnets 0. Please send the support request to extend the quota using Azure portal: aka.ms/sql-mi-obtain-larger-quota'
```

This is from the `./sql-database/failover-groups/add-managed-instance-to-failover-group-az-ps.ps1`. I understand that this script demonstrates a fairly complex and useful thing to do, but I'm unable to test it. That means that I'm not sure if it's fit for general user consumption or even behaves properly.

**Comment by MashaMSFT** [comment]
Hi @sptramer, can you please confirm that a.  you're using east us and east us 2 as the two locations, and that you have requested a quota increase from here: aka.ms/sql-mi-obtain-larger-quota ?

**Comment by sptramer** [comment]
Yes, correctly using `eastus` and `eastus2`. When I asked for increased capacity through support as described on the article at that aka.ms link, I received an answer that my account was already configured to have appropriate limits for testing. I can try again, I guess?

I should also say that this is a situation that would be very easy for a user to encounter, so please make it clear in the scripts (through a comment) how a quota increase can be requested.

**Comment by MashaMSFT** [comment]
@sptramer, interesting... there is a subnet restriction. Can you check the virtual networks that exist in  your subscription, and see if there are any that you can delete? I've run into this issue also...  but I was able to increase our quota and it was fine after that :( You're right though I'll add a note to the script. It's such a pain... Welcome to managed instances :) .......

**Comment by sptramer** [comment]
@MashaMSFT Everything has passed test! If there are further copy-only edits to make, please do so, and I will merge when they're completed. Thanks for providing me with access to the SQL test account, that sped things up quite a bit.

**Comment by MashaMSFT** [comment]
Hi @sptramer, i think the script is good as it is, unless you saw any thing that needed to be edited? If not, let's go ahead and merge it :) thanks!

**Comment by sptramer** [comment]
Merged, thanks for your patience while I dealt with the quota issues.

**Pull request merged**
