### PR TITLE
http to https

### PR DESCRIPTION
**Pull request by CarlRabeler**
## CHECKLIST

- [x] This pull request was tested on:
  - [ ] PowerShell 5.1 on Windows
  - [x] PowerShell 6.x on Windows
  - [ ] PowerShell 6.x on Linux
- [x] Resources not created by the scripts in the pull request are __explicitly__ mentioned in a comment at the head of the file, __and__ have user-supplied variables or function arguments which correspond to the required resource identifiers.
- [x] All user-supplied values are set in variables at the head of the file, after any comments.
- [x] All passwords are user-supplied values, or generated by a secure random string generator.
- [x] All Azure identifiers required to be universally unique are guaranteed to be so. 
- [x] All scripts only use commands available in the latest release of the Azure PowerShell `Az` module. ([Command reference](https://docs.microsoft.com/en-us/powershell/module/?term=Az.))
  - [ ] I have an exception! (__optional__ - state for which service)
  - [ ] I'm requesting an exception! (__optional__ - you must include your MS alias for further discussion before PR review)
- [x] All scripts contain only ASCII characters (no 'smart quotes' or other wide characters)

### CODE REVIEW

**Comment by CarlRabeler** [comment]
@sptramer please merge this tiny change

**Comment by CarlRabeler** [comment]
#sign-off

**Comment by sptramer** [comment]
@CarlRabeler Please make sure the checklist is filled out. PRs without complete checklists will not be processed and will be closed after 7 days.

**Comment by CarlRabeler** [comment]
#sign-off

**Comment by CarlRabeler** [comment]
@sptramer please merge

**Pull request merged**
