### PR TITLE
Dependencies powershell and powerBI template

### PR DESCRIPTION
**Pull request by musa-57**
## Checklist

- [ ] This pull request was tested on __both of__:
  - [X] PowerShell 5.1 (Windows)
  - [ ] PowerShell 6.x
  - [ ] PowerShell 7.x ([Latest PowerShell](https://github.com/PowerShell/PowerShell/releases))
- [X] Scripts do not contain static passwords or other secret tokens.
- [X] All Azure resource identifiers which must be universally unique are guaranteed to be so.

### Testing information

Platform and PowerShell version: `[pscustomobject]$PSVersionTable | Select-Object OS, BuildVersion, PSVersion`

OS BuildVersion PSVersion
-- ------------ ---------
   10.0.19041.1 5.1.19041.1

Az version: `(Get-InstalledModule -Name Az).Version`

Major  Minor  Build  Revision
-----  -----  -----  --------
4      4      0      -1

### CODE REVIEW

**Comment by musa-57** [comment]
#sign-off

**Comment by musa-57** [comment]
@mikefrobbins - We are going to be announcing these at Ignite. Would appreciate it if these are reviewed soon.

**Comment by musa-57** [comment]
#sign-off

**Review by mikefrobbins — APPROVED** [review]
Approving since this is for Ignite. Suggestions for improvement based on PowerShell best practices include:
* Use a compound Where-Object statement instead of multiple Where-Object's.
* Avoid string concatenation.
* Use Verb-Noun for all exported functions.
* Add a module manifest (PSD1 file). A manifest contains metadata about the module. This is important because the version number is specified in the manifest. Without a manifest, customers won't know when an updated version of the module is released. All modules without a manifest show as version 0.0.
* A single Export-ModuleMember can be used at the end of the file. Or the exported functions can be specified in the FunctionsToExport section of a module manifest.

**Comment by musa-57** [comment]
Thanks Mike. Will address in the next couple of weeks.

**Pull request merged**
