### PR TITLE
ACR] Update to service principal create script

### PR DESCRIPTION
**Pull request by dlepow**
## DESCRIPTION

Update to script to create service principal for Azure Container Registry. New-AzADServicePrincipal handles secure passwords differently than legacy New-AzureRmADServicePrincipal cmdlet.

## CHECKLIST

- [X] This pull request was tested on:
  - [X] PowerShell 5.1 on Windows
  - [ ] PowerShell 6.x on Windows
  - [X] PowerShell 6.x on Linux [Azure Cloud Shell]
- [ ] Resources not created by the scripts in the pull request are __explicitly__ mentioned in a comment at the head of the file, __and__ have user-supplied variables or function arguments which correspond to the required resource identifiers.
- [X] All user-supplied values are set in variables at the head of the file, after any comments.
- [X] All passwords are user-supplied values, or generated by a secure random string generator.
- [ ] All Azure identifiers required to be universally unique are guaranteed to be so. 
- [X] All scripts only use commands available in the latest release of the Azure PowerShell `Az` module. ([Command reference](https://docs.microsoft.com/en-us/powershell/module/?term=Az.))
  - [ ] I have an exception! (__optional__ - state for which service)
  - [ ] I'm requesting an exception! (__optional__ - you must include your MS alias for further discussion before PR review)

### CODE REVIEW

**Comment by dlepow** [comment]
Fixes https://github.com/MicrosoftDocs/azure-docs/issues/30225

**Comment by dlepow** [comment]
@sptramer - If this looks OK to you, pls merge. Thanks!

**Comment by sptramer** [comment]
@dlepow You are required to fill in the checklist before PR evaluation. Please do so.

**Comment by sptramer** [comment]
@dlepow I got a little confused about the checklist because of how github formats the markdown: If you manually check the boxes, please make sure that there's no spaces inside the brackets from now on.

The following requirements still need to be signed off on before PR review:

* Required resources are mentioned at the head of the script (check this even if your script has no pre-reqs)
* Required universally unique IDs (please check, even if none in script)
* ASCII-only (please check - you can validate [with this script](https://lazywinadmin.com/2015/08/powershell-remove-special-characters.html#) for now but I will provide a tool soon.)

Sorry for any confusion, this is the first PR using the new checklist - I'll make sure that I clarify some of the language.

**Comment by sptramer** [comment]
@dlepow Ignore the ASCII-only remark: If the script was tested and confirmed to run on 5.1 it's clean. Still need sign-off on the ACR name uniqueness.

**Comment by dlepow** [comment]
@sptramer - Yes, ACR does require a unique ID per registry. This script does not create a registry, but rather assumes a customer is bringing a user-supplied value. This is specified a the head of the script along with other user-supplied values. Please let me know if this meets your requirement. Thanks!

**Comment by sptramer** [comment]
@dlepow Merged - thanks for bearing with the new checklist process. I'll be making sure that the checklist criteria are clearer for edits vs. new scripts, and have it be clearer about which boxes should be checked (and why).

**Pull request merged**
