### PR TITLE
Remove unsured variables and fix variable wrong names

### PR DESCRIPTION
**Pull request by kozhemyak**
## Description

- Fix variable typo 'ExistingLocation' in `log-analytics-create-new-resource.ps1`
- Remove unused variable `location` in `delete-containers-by-prefix.ps1`
- Remove unused variable `ContainerName` in `PostStorageLogs2LogAnalytics.ps1`
- Make long one-line script more readble in `create-managed-disk-from-snapshot.ps1`
- Added misssed variable `-DiskSizeGB $diskSize` in `create-managed-disks-from-vhd-in-different-subscription.ps1`
- Added misssed variable `-DiskSizeGB $diskSize` in `create-managed-disk-from-snapshot.ps1`
- Fix variable type `nsgfe` in `vm-with-two-nics.ps1`

## Checklist

- [ ] This pull request was tested on __both of__:
  - [X] PowerShell 5.1 (Windows)
  - [ ] PowerShell 6.x
  - [ ] PowerShell 7.x ([Latest PowerShell](https://github.com/PowerShell/PowerShell/releases))
- [X] Scripts do not contain static passwords or other secret tokens.
- [X] All Azure resource identifiers which must be universally unique are guaranteed to be so.

### Testing information

Platform and PowerShell version: `[pscustomobject]$PSVersionTable | Select-Object OS, BuildVersion, PSVersion`
```
OS BuildVersion   PSVersion
-- ------------   ---------
   10.0.19041.610 5.1.19041.610
```
Az version: `(Get-InstalledModule -Name Az).Version`
```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      7      0      -1
```

### CODE REVIEW

**Comment by mikefrobbins** [comment]
@kozhemyak Please comment with `#sign-off` when you're ready for this PR to be merged.

**Comment by kozhemyak** [comment]
#sign-off pull request is ready to be merged.

**Review by mikefrobbins — APPROVED** [review]
LGTM

**Comment by kozhemyak** [comment]
#sign-off pull request is ready to be merged.

**Comment by kozhemyak** [comment]
Thanks

**Pull request merged**
