### PR TITLE
Update AzMig_Dependencies.psm1

### PR DESCRIPTION
**Pull request by martyncoup**
Changed TokenCache behaviour now that is depricated and removed redundant assignment of the TokenCacheItem variable.

## Checklist

- [X] This pull request was tested on __both of__:
  - [X] PowerShell 5.1 (Windows)
  - [X] PowerShell 6.x
  - [X] PowerShell 7.x ([Latest PowerShell](https://github.com/PowerShell/PowerShell/releases))
- [X] Scripts do not contain static passwords or other secret tokens.
- [X] All Azure resource identifiers which must be universally unique are guaranteed to be so.

### Testing information

Platform and PowerShell version: `[pscustomobject]$PSVersionTable | Select-Object OS, BuildVersion, PSVersion`
OS BuildVersion    PSVersion
-- ------------    ---------
   10.0.18362.1171 5.1.18362.1171

Az version: `(Get-InstalledModule -Name Az).Version`
Major  Minor  Build  Revision
-----  -----  -----  --------
5      2      0      -1

### CODE REVIEW

**Comment by dcaro** [comment]
@martyncoup `Get-AzAccessToken` cmdlet is only available with Az.Accounts 2.2.0 or later. May I suggest that you add a verification step or a note in the readme that clarify the required version? 
Other than that, the code change looks good to me.

**Comment by martyncoup** [comment]
Great shout @dcaro, I missed that one, I've made the appropriate changes.

**Comment by pvrk** [comment]
@dcaro : Thanks for pulling me in. But can you please clarify the PS sample file name for which the changes are proposed? I am not able to relate/understand which sample file is being used.

**Comment by pvrk** [comment]
To clarify, The only sample file we have in this repository is “backup/backup-encrypted-vm/backup-encrypted-vm.ps1”

This PR is on the file “azure-migrate/dependencies-at-scale/AzMig_Dependencies.psm1”

We don’t use token in our script and we don’t own the above file. So, not sure what is our (Az Backup team’s) action point.

**Review by mikefrobbins — APPROVED** [review]
LGTM

**Pull request merged**
