### PR TITLE
(AzureCXP)MicrosoftDocs/azure-docs#33020

### PR DESCRIPTION
**Pull request by SubhashVasarapu-MSFT**
## Description

Typos in the code

### Required

- [ ] This pull request was tested on __both of__:
  - [x] PowerShell 5.1 (Windows)
  - [ ] The latest non-preview Powershell. ([Latest PowerShell](https://github.com/PowerShell/PowerShell/releases))
    - __PowerShell version__ (`$PSVersionTable.PSVersion`):
- [x] This pull request was tested with the latest version of the `Az` module. ([Latest version](https://docs.microsoft.com/powershell/azure/release-notes-azureps))
  - __Az module version__ (`(Get-InstalledModule -Name Az).Version`): 
- [x] The scripts in this pull request use only `Az` commands.
  - [ ] I have an exemption (explained in the __Optional__ section)
- [ ] Scripts do not contain static passwords or other secret tokens.
  - [ ] New passwords are automatically generated (by `New-Guid` or another secure RNG method)
  - [ ] Existing secrets are user-supplied
- [ ] All prerequisite resources are listed in comments at the top of the scripts.
- [ ] All required imports are at the top of scripts, below prerequisites.
- [ ] All user-set variables are at the top of scripts, below imports.
- [ ] All identifiers which must be universally unique are guaranteed to be so.
- [ ] All scripts use UNIX-style line endings (LF) ([Instructions](https://help.github.com/articles/dealing-with-line-endings))

### Optional

- [ ] User-set variables have initial values guaranteed to cause the script to fail.  
- [ ] This PR requires AzureRM because:
  - [ ] Scripts use a preview module only available for AzureRM
    - __List of preview modules and versions__:
  - [ ] Scripts use service(s) not fully supported in Az
    - __List of services__:
  - [ ] Touches services which have an exemption from the Az requirement
    - __List of services__:
  - [ ] Scripts use the classic deployment model
  - [ ] Scripts use Azure Stack
  - [ ] Other (please explain):

### CODE REVIEW

**Comment by SubhashVasarapu-MSFT** [comment]
Here is a pull request awaiting for merge and the corrections in the code are very minimal like removing the trailing A's from the code.

**Comment by SubhashVasarapu-MSFT** [comment]
@erickson-doug , I have raised this PR to fix a few typos in the powershell script. Could you please review and sign off on this?

**Comment by sptramer** [comment]
@SubhashVasarapu-MSFT The following items must be completed in the REQUIRED checklist before pull request processing can begin:

* Testing on PowerShell 5.1
* All prerequisite resources are listed in comments at the top of the scripts.
* All required imports are at the top of scripts, below prerequisites.
* All user-set variables are at the top of scripts, below imports.
* All identifiers which must be universally unique are guaranteed to be so.
* Scripts do not contain static passwords or other secret tokens. 
* LF line endings

**Comment by sptramer** [comment]
@SubhashVasarapu-MSFT Pull requests which have not had the pull request checklist completed within the 7-day period are closed. You are welcome to re-open the pull request when the checklist has been completed.

**Comment by sptramer** [comment]
Reopening since this meets the criteria established under the new checklist. Now in review.

**Comment by sptramer** [comment]
@SubhashVasarapu-MSFT Running the script with AzPS v2.3.2 also shows the following warnings, which should be resolved:

```
WARNING: Breaking changes in the cmdlet 'New-AzFirewall' :
WARNING:  - The parameter : 'VirtualNetworkName' is being replaced by parameter : 'VirtualNetwork'.
        The type of the parameter is changing from 'System.String' to 'PSVirtualNetwork'.


WARNING:        Change description : This parameter will be removed in an upcoming breaking change release. After this point the Virtual Network will be provided as an object instead of a string.   

WARNING: Note :The change is expected to take effect from the version :  '2.0.0'


        New Way : New-AzFirewall -VirtualNetwork $vnet
WARNING:  - The parameter : 'PublicIpName' is being replaced by parameter : 'PublicIpAddress'.
        The type of the parameter is changing from 'System.String' to 'List<PSPublicIpAddress>'.


WARNING:        Change description : This parameter will be removed in an upcoming breaking change release. After this point the Public IP Address will be provided as a list of one or more objects instead of a string.
WARNING: Note :The change is expected to take effect from the version :  '2.0.0'


WARNING: Cmdlet invocation changes :
        Old Way : New-AzFirewall -PublicIpName "public-ip-name"
        New Way : New-AzFirewall -PublicIpAddress @($publicip1, $publicip2)
WARNING: NOTE : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.
```

**Comment by sptramer** [comment]
Re-reviewing. This PR does handle a critical UTF-8 issue. Deprecation and uniqueness issues can be handled in a cleanup PR. Merging.

**Pull request merged**
